### ISSUE TITLE
Skip htmlpreview by putting switching to the gh-pages branch

### ISSUE THREAD

**Issue by lindell** [teebu/HearstoneSolitaire#1]
If you just move everything in this repo to the "gh-pages" branch instead of the master branch you don't have to use http://htmlpreview.github.io/.

I did this in a forked repo here:
https://github.com/lindell/HearstoneSolitaire

This will automatically host the page on <username>.github.io/HearstoneSolitaire
Like:
http://lindell.github.io/HearstoneSolitaire
(I make my github page redirect to my website which makes the website change address to lindell.me/HearstoneSolitaire)

**Comment by teebu** [comment]
Thanks. I didn't know about that feature. And yes, I did noticed you renamed it to index.html.

http://teebu.github.io/HearstoneSolitaire/ works. 

I just realized I called it Hearstone.
